// Code generated by Kitex v0.9.1. DO NOT EDIT.
package imgateway

import (
	server "github.com/cloudwego/kitex/server"
	imrelay "pigeon/kitex_gen/service/imrelay"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler imrelay.IMGateway, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler imrelay.IMGateway, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
