# grpc为内部集群提供接口, 如向某个session发送消息
rpc-server:
  host: 0.0.0.0
  port: 5001

# 做服务发现的, 可以用来服务发现im-auth-route的ipport以及im-relay的ipport
# 也可以上报自己的metrics, 让ipconf感知到gateway的性能指标变化
etcd:
  -
    host: 127.0.0.1
    port: 2379

# 会读消息库, pull消息走im relay
mysql:
  host: 127.0.0.1
  port: 3306
  user: debian-sys-maint
  pwd : 8B2e4SuzKFCpn7AD
  db: im_chatevloop

# 业务相关配置
app:
  debug: true
  # 对外提供服务的ip:port
  advertise-addrport: "127.0.0.1:5001"
