// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package base

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *SessionEntry) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SessionEntry[number], err)
}

func (x *SessionEntry) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.LoginAt, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *SessionEntry) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Username, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SessionEntry) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.SessionId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SessionEntry) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.DeviceDesc, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SessionEntry) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.GwAdvertiseAddrPort, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SessionEntry) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *SessionEntry) fastWriteField1(buf []byte) (offset int) {
	if x.LoginAt == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetLoginAt())
	return offset
}

func (x *SessionEntry) fastWriteField2(buf []byte) (offset int) {
	if x.Username == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetUsername())
	return offset
}

func (x *SessionEntry) fastWriteField3(buf []byte) (offset int) {
	if x.SessionId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetSessionId())
	return offset
}

func (x *SessionEntry) fastWriteField4(buf []byte) (offset int) {
	if x.DeviceDesc == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetDeviceDesc())
	return offset
}

func (x *SessionEntry) fastWriteField5(buf []byte) (offset int) {
	if x.GwAdvertiseAddrPort == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetGwAdvertiseAddrPort())
	return offset
}

func (x *SessionEntry) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *SessionEntry) sizeField1() (n int) {
	if x.LoginAt == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetLoginAt())
	return n
}

func (x *SessionEntry) sizeField2() (n int) {
	if x.Username == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetUsername())
	return n
}

func (x *SessionEntry) sizeField3() (n int) {
	if x.SessionId == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetSessionId())
	return n
}

func (x *SessionEntry) sizeField4() (n int) {
	if x.DeviceDesc == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetDeviceDesc())
	return n
}

func (x *SessionEntry) sizeField5() (n int) {
	if x.GwAdvertiseAddrPort == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetGwAdvertiseAddrPort())
	return n
}

var fieldIDToName_SessionEntry = map[int32]string{
	1: "LoginAt",
	2: "Username",
	3: "SessionId",
	4: "DeviceDesc",
	5: "GwAdvertiseAddrPort",
}
