// Code generated by Kitex v0.11.3. DO NOT EDIT.

package imauthroute

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	imauthroute "pigeon/kitex_gen/service/imauthroute"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, Req *imauthroute.LoginReq, callOptions ...callopt.Option) (r *imauthroute.LoginResp, err error)
	Logout(ctx context.Context, Req *imauthroute.LogoutReq, callOptions ...callopt.Option) (r *imauthroute.LogoutResp, err error)
	ForceOffline(ctx context.Context, Req *imauthroute.ForceOfflineReq, callOptions ...callopt.Option) (r *imauthroute.ForceOfflineResp, err error)
	QuerySessionRoute(ctx context.Context, Req *imauthroute.QuerySessionRouteReq, callOptions ...callopt.Option) (r *imauthroute.QuerySessionRouteResp, err error)
	QueryUserRoute(ctx context.Context, Req *imauthroute.QueryUserRouteReq, callOptions ...callopt.Option) (r *imauthroute.QueryUserRouteResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kIMAuthRouteClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kIMAuthRouteClient struct {
	*kClient
}

func (p *kIMAuthRouteClient) Login(ctx context.Context, Req *imauthroute.LoginReq, callOptions ...callopt.Option) (r *imauthroute.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kIMAuthRouteClient) Logout(ctx context.Context, Req *imauthroute.LogoutReq, callOptions ...callopt.Option) (r *imauthroute.LogoutResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, Req)
}

func (p *kIMAuthRouteClient) ForceOffline(ctx context.Context, Req *imauthroute.ForceOfflineReq, callOptions ...callopt.Option) (r *imauthroute.ForceOfflineResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ForceOffline(ctx, Req)
}

func (p *kIMAuthRouteClient) QuerySessionRoute(ctx context.Context, Req *imauthroute.QuerySessionRouteReq, callOptions ...callopt.Option) (r *imauthroute.QuerySessionRouteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QuerySessionRoute(ctx, Req)
}

func (p *kIMAuthRouteClient) QueryUserRoute(ctx context.Context, Req *imauthroute.QueryUserRouteReq, callOptions ...callopt.Option) (r *imauthroute.QueryUserRouteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryUserRoute(ctx, Req)
}
