// Code generated by Kitex v0.11.3. DO NOT EDIT.
package imgateway

import (
	server "github.com/cloudwego/kitex/server"
	imgateway "pigeon/kitex_gen/service/imgateway"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler imgateway.IMGateway, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler imgateway.IMGateway, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
