// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: service/im-chat-evloop.proto

package imchatevloop

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "pigeon/kitex_gen/service/base"
	evloopio "pigeon/kitex_gen/service/evloopio"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建群组, 由im-relation调用
type CreateGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      int64  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	GroupId      string `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	GroupOwnerId string `protobuf:"bytes,3,opt,name=group_owner_id,json=groupOwnerId,proto3" json:"group_owner_id,omitempty"`
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_im_chat_evloop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_im_chat_evloop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_service_im_chat_evloop_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CreateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateGroupRequest) GetGroupOwnerId() string {
	if x != nil {
		return x.GroupOwnerId
	}
	return ""
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_im_chat_evloop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_im_chat_evloop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_service_im_chat_evloop_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateGroupResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UniversalGroupEvloopRequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int64                               `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	GroupId string                              `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Input   *evloopio.UniversalGroupEvloopInput `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *UniversalGroupEvloopRequestReq) Reset() {
	*x = UniversalGroupEvloopRequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_im_chat_evloop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniversalGroupEvloopRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalGroupEvloopRequestReq) ProtoMessage() {}

func (x *UniversalGroupEvloopRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_im_chat_evloop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversalGroupEvloopRequestReq.ProtoReflect.Descriptor instead.
func (*UniversalGroupEvloopRequestReq) Descriptor() ([]byte, []int) {
	return file_service_im_chat_evloop_proto_rawDescGZIP(), []int{2}
}

func (x *UniversalGroupEvloopRequestReq) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UniversalGroupEvloopRequestReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UniversalGroupEvloopRequestReq) GetInput() *evloopio.UniversalGroupEvloopInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type UniversalGroupEvloopRequestResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool                                 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Version int64                                `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Output  *evloopio.UniversalGroupEvloopOutput `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *UniversalGroupEvloopRequestResp) Reset() {
	*x = UniversalGroupEvloopRequestResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_im_chat_evloop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniversalGroupEvloopRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalGroupEvloopRequestResp) ProtoMessage() {}

func (x *UniversalGroupEvloopRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_im_chat_evloop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversalGroupEvloopRequestResp.ProtoReflect.Descriptor instead.
func (*UniversalGroupEvloopRequestResp) Descriptor() ([]byte, []int) {
	return file_service_im_chat_evloop_proto_rawDescGZIP(), []int{3}
}

func (x *UniversalGroupEvloopRequestResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UniversalGroupEvloopRequestResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UniversalGroupEvloopRequestResp) GetOutput() *evloopio.UniversalGroupEvloopOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_service_im_chat_evloop_proto protoreflect.FileDescriptor

var file_service_im_chat_evloop_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6d, 0x2d, 0x63, 0x68, 0x61,
	0x74, 0x2d, 0x65, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x69, 0x6d, 0x63, 0x68, 0x61, 0x74, 0x65, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x1a, 0x0f, 0x62, 0x61,
	0x73, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x62,
	0x61, 0x73, 0x65, 0x2f, 0x65, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x49, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x90, 0x01,
	0x0a, 0x1e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x45, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x69, 0x6f, 0x2e,
	0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76,
	0x6c, 0x6f, 0x6f, 0x70, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x22, 0x93, 0x01, 0x0a, 0x1f, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x45, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x76, 0x6c, 0x6f, 0x6f,
	0x70, 0x69, 0x6f, 0x2e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x45, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x06,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0xde, 0x01, 0x0a, 0x0c, 0x49, 0x4d, 0x43, 0x68, 0x61,
	0x74, 0x45, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x12, 0x52, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x20, 0x2e, 0x69, 0x6d, 0x63, 0x68, 0x61, 0x74, 0x65,
	0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6d, 0x63, 0x68, 0x61,
	0x74, 0x65, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7a, 0x0a, 0x1b, 0x55,
	0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x6c,
	0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x2e, 0x69, 0x6d, 0x63,
	0x68, 0x61, 0x74, 0x65, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x2e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x2d, 0x2e, 0x69, 0x6d, 0x63, 0x68, 0x61,
	0x74, 0x65, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x2e, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x6c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x27, 0x5a, 0x25, 0x70, 0x69, 0x67, 0x65, 0x6f,
	0x6e, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x69, 0x6d, 0x63, 0x68, 0x61, 0x74, 0x65, 0x76, 0x6c, 0x6f, 0x6f, 0x70,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_im_chat_evloop_proto_rawDescOnce sync.Once
	file_service_im_chat_evloop_proto_rawDescData = file_service_im_chat_evloop_proto_rawDesc
)

func file_service_im_chat_evloop_proto_rawDescGZIP() []byte {
	file_service_im_chat_evloop_proto_rawDescOnce.Do(func() {
		file_service_im_chat_evloop_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_im_chat_evloop_proto_rawDescData)
	})
	return file_service_im_chat_evloop_proto_rawDescData
}

var file_service_im_chat_evloop_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_im_chat_evloop_proto_goTypes = []interface{}{
	(*CreateGroupRequest)(nil),                  // 0: imchatevloop.CreateGroupRequest
	(*CreateGroupResponse)(nil),                 // 1: imchatevloop.CreateGroupResponse
	(*UniversalGroupEvloopRequestReq)(nil),      // 2: imchatevloop.UniversalGroupEvloopRequestReq
	(*UniversalGroupEvloopRequestResp)(nil),     // 3: imchatevloop.UniversalGroupEvloopRequestResp
	(*evloopio.UniversalGroupEvloopInput)(nil),  // 4: evloopio.UniversalGroupEvloopInput
	(*evloopio.UniversalGroupEvloopOutput)(nil), // 5: evloopio.UniversalGroupEvloopOutput
}
var file_service_im_chat_evloop_proto_depIdxs = []int32{
	4, // 0: imchatevloop.UniversalGroupEvloopRequestReq.input:type_name -> evloopio.UniversalGroupEvloopInput
	5, // 1: imchatevloop.UniversalGroupEvloopRequestResp.output:type_name -> evloopio.UniversalGroupEvloopOutput
	0, // 2: imchatevloop.IMChatEvloop.CreateGroup:input_type -> imchatevloop.CreateGroupRequest
	2, // 3: imchatevloop.IMChatEvloop.UniversalGroupEvloopRequest:input_type -> imchatevloop.UniversalGroupEvloopRequestReq
	1, // 4: imchatevloop.IMChatEvloop.CreateGroup:output_type -> imchatevloop.CreateGroupResponse
	3, // 5: imchatevloop.IMChatEvloop.UniversalGroupEvloopRequest:output_type -> imchatevloop.UniversalGroupEvloopRequestResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_im_chat_evloop_proto_init() }
func file_service_im_chat_evloop_proto_init() {
	if File_service_im_chat_evloop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_im_chat_evloop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_im_chat_evloop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_im_chat_evloop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniversalGroupEvloopRequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_im_chat_evloop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniversalGroupEvloopRequestResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_im_chat_evloop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_im_chat_evloop_proto_goTypes,
		DependencyIndexes: file_service_im_chat_evloop_proto_depIdxs,
		MessageInfos:      file_service_im_chat_evloop_proto_msgTypes,
	}.Build()
	File_service_im_chat_evloop_proto = out.File
	file_service_im_chat_evloop_proto_rawDesc = nil
	file_service_im_chat_evloop_proto_goTypes = nil
	file_service_im_chat_evloop_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.9.1. DO NOT EDIT.

type IMChatEvloop interface {
	CreateGroup(ctx context.Context, req *CreateGroupRequest) (res *CreateGroupResponse, err error)
	UniversalGroupEvloopRequest(ctx context.Context, req *UniversalGroupEvloopRequestReq) (res *UniversalGroupEvloopRequestResp, err error)
}
