// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package imrelay

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *BizMessageReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_BizMessageReq[number], err)
}

func (x *BizMessageReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Biz, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *BizMessageReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.EchoCode, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *BizMessageReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Data, offset, err = fastpb.ReadBytes(buf, _type)
	return offset, err
}

func (x *BizMessageResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
}

func (x *BizMessageReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *BizMessageReq) fastWriteField1(buf []byte) (offset int) {
	if x.Biz == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetBiz())
	return offset
}

func (x *BizMessageReq) fastWriteField2(buf []byte) (offset int) {
	if x.EchoCode == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetEchoCode())
	return offset
}

func (x *BizMessageReq) fastWriteField3(buf []byte) (offset int) {
	if len(x.Data) == 0 {
		return offset
	}
	offset += fastpb.WriteBytes(buf[offset:], 3, x.GetData())
	return offset
}

func (x *BizMessageResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	return offset
}

func (x *BizMessageReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *BizMessageReq) sizeField1() (n int) {
	if x.Biz == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetBiz())
	return n
}

func (x *BizMessageReq) sizeField2() (n int) {
	if x.EchoCode == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetEchoCode())
	return n
}

func (x *BizMessageReq) sizeField3() (n int) {
	if len(x.Data) == 0 {
		return n
	}
	n += fastpb.SizeBytes(3, x.GetData())
	return n
}

func (x *BizMessageResp) Size() (n int) {
	if x == nil {
		return n
	}
	return n
}

var fieldIDToName_BizMessageReq = map[int32]string{
	1: "Biz",
	2: "EchoCode",
	3: "Data",
}

var fieldIDToName_BizMessageResp = map[int32]string{}
