# grpc为内部集群提供接口,
rpc-server:
  host: 0.0.0.0
  port: 4001

# 做服务发现的, 可以用来服务发现im-auth-route的ipport以及im-relay的ipport
# 也可以上报自己的metrics, 让ipconf感知到gateway的性能指标变化
etcd:
  -
    host: 127.0.0.1
    port: 2379

# 用来存储用户路由信息, 做分布式锁
redis:
  host: 127.0.0.1
  port: 6379
  keyprefix: im_auth_route/

# 用来存储用户信息
mysql:
  host: 127.0.0.1
  port: 3306
  user: debian-sys-maint
  pwd : 8B2e4SuzKFCpn7AD
  db: im_auth_route

  # 业务相关配置
app:
  # 路由服务对外提供rpc服务的地址
  rpc-advertise-addrport: "127.0.0.1:4001"
  # 同一username上线设备限制, -1为不限制
  device-num-limit: -1

# 用来接收下线通知
mq: