// Code generated by Kitex v0.11.3. DO NOT EDIT.

package imrelay

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	imrelay "pigeon/kitex_gen/service/imrelay"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	BizMessage(ctx context.Context, Req *imrelay.BizMessageReq, callOptions ...callopt.Option) (r *imrelay.BizMessageResp, err error)
	CreateChatEventLoop(ctx context.Context, Req *imrelay.CreateChatEventLoopReq, callOptions ...callopt.Option) (r *imrelay.CreateChatEventLoopResp, err error)
	RedirectToChatEventLoop(ctx context.Context, Req *imrelay.RedirectToChatEventLoopReq, callOptions ...callopt.Option) (r *imrelay.RedirectToChatEventLoopResp, err error)
	GetLastVersionConfig(ctx context.Context, Req *imrelay.GetLastVersionConfigReq, callOptions ...callopt.Option) (r *imrelay.GetLastVersionConfigResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kIMRelayClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kIMRelayClient struct {
	*kClient
}

func (p *kIMRelayClient) BizMessage(ctx context.Context, Req *imrelay.BizMessageReq, callOptions ...callopt.Option) (r *imrelay.BizMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BizMessage(ctx, Req)
}

func (p *kIMRelayClient) CreateChatEventLoop(ctx context.Context, Req *imrelay.CreateChatEventLoopReq, callOptions ...callopt.Option) (r *imrelay.CreateChatEventLoopResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateChatEventLoop(ctx, Req)
}

func (p *kIMRelayClient) RedirectToChatEventLoop(ctx context.Context, Req *imrelay.RedirectToChatEventLoopReq, callOptions ...callopt.Option) (r *imrelay.RedirectToChatEventLoopResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RedirectToChatEventLoop(ctx, Req)
}

func (p *kIMRelayClient) GetLastVersionConfig(ctx context.Context, Req *imrelay.GetLastVersionConfigReq, callOptions ...callopt.Option) (r *imrelay.GetLastVersionConfigResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLastVersionConfig(ctx, Req)
}
